### ISSUE TITLE
Server segfaults during fights

### ISSUE THREAD

**Issue by benmwebb** [benmwebb/dopewars#9]
During a fight, server will segfault:

\(This is the log from the AI bot right before the 
crash:\)

Jetting to Lexington with $1 cash and $9,680 debt
Sheriff Hege and 3 deputies - pitifully armed - are 
chasing you, man\!
Sheriff Hege hits you, man\!
Sheriff Hege hits you, man\!

and here's what gdb says:

rogram received signal SIGSEGV, Segmentation fault.
0x12000f408 in ServerLoop \(\) at serverside.c:832
832              /\*if \(tmp &amp;amp;&amp;amp; FD\_ISSET\(tmp-
&amp;gt;fd,&amp;amp;errorfs\)\) \{
\(gdb\) where
\#0  0x12000f408 in ServerLoop \(\) at serverside.c:832
\#1  0x120008334 in main \(argc=2, argv=0x1fffffa00\) at 
dopewars.c:1717

\(gdb\) print tmp-&amp;gt;fd
$1 = 538141120
\(gdb\) print &amp;amp;errorfs
$2 = \(fd\_set \*\) 0x1fffff958
\(gdb\) print tmp
$3 = \(Player \*\) 0x120152030

Attached is my /etc/dopewars

Reported by: spazzz

**Comment by ivanfuhr** [comment]
Agent started handling this issue.

- Repository: `benmwebb/dopewars`
- Operation: `bugfix`
- Dry run: `true`
- Workspace: `/workspaces/benmwebb__dopewars`
- Planned steps: 6
- PR draft branch: `agent/issue-9-bugfix`
